/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculofatorial;

/**
 *
 * @author Ronan
 */
public class fatorial extends javax.swing.JFrame {

    /**
     * Creates new form fatorial
     */
    public fatorial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spinnerNum = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        lblFatorial = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCalc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        spinnerNum.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        spinnerNum.setModel(new javax.swing.SpinnerNumberModel(0, 0, 12, 1));
        spinnerNum.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerNumStateChanged(evt);
            }
        });
        getContentPane().add(spinnerNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 60, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("!=");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        lblFatorial.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblFatorial.setText("1");
        getContentPane().add(lblFatorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 130, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Exclamao 2.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        lblCalc.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCalc.setForeground(new java.awt.Color(0, 102, 255));
        lblCalc.setText("jLabel2");
        getContentPane().add(lblCalc, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 180, 200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spinnerNumStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerNumStateChanged
        int num  = Integer.parseInt(spinnerNum.getValue().toString());
        int fat  = 1;
        int cont = num;
        String resultado = cont  + " x ";
        String mult = " x ";
        
        if(cont == 0){
            resultado += 1;
        }
        
        while(cont >= 1){
            fat *= cont;
            resultado += --cont + mult;
            cont --;
        }
        
        lblFatorial.setText(Integer.toString(fat));
        lblCalc.setText(resultado);
    }//GEN-LAST:event_spinnerNumStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fatorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fatorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fatorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fatorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fatorial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCalc;
    private javax.swing.JLabel lblFatorial;
    private javax.swing.JSpinner spinnerNum;
    // End of variables declaration//GEN-END:variables
}
