algoritmo "Divisões"
// Função :
// Autor :
// Data : 22/11/2014
// Seção de Declarações 
var
   n1,n2,DN,DI,R:real
inicio
// Seção de Comandos
   Escreva("Digite a primeira nota: ")
   Leia (n1)
   Escreva ("Digite a segunada nota: ")
   Leia (n2)
        DN <- n1/n2
        DI <- n1\n2
        R  <- n1%n2
   Escreval ("Divisão norma: ",DN)
   Escreval ("Divisaõ Inteira: ",DI)
   Escreva ("Resto da divisão:",R)

fimalgoritmo
